class CurrencyNotFoundError(Exception): ...


class CurrencyCodeAlreadyExistsError(Exception): ...


class ExchangeRateNotFoundError(Exception): ...


class ExchangeRateAlreadyExistsError(Exception): ...
